# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hari/Documents/Projects/RISC-V/Verilog_implementations/RV32I_SSP/RV32I_SSP.srcs/sources_1/ip/clk_divider/clk_divider.xci
# IP: The module: 'clk_divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hari/Documents/Projects/RISC-V/Verilog_implementations/RV32I_SSP/RV32I_SSP.srcs/sources_1/ip/clk_divider/clk_divider_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divider'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/hari/Documents/Projects/RISC-V/Verilog_implementations/RV32I_SSP/RV32I_SSP.srcs/sources_1/ip/clk_divider/clk_divider.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/hari/Documents/Projects/RISC-V/Verilog_implementations/RV32I_SSP/RV32I_SSP.srcs/sources_1/ip/clk_divider/clk_divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/hari/Documents/Projects/RISC-V/Verilog_implementations/RV32I_SSP/RV32I_SSP.srcs/sources_1/ip/clk_divider/clk_divider.xci
# IP: The module: 'clk_divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hari/Documents/Projects/RISC-V/Verilog_implementations/RV32I_SSP/RV32I_SSP.srcs/sources_1/ip/clk_divider/clk_divider_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/hari/Documents/Projects/RISC-V/Verilog_implementations/RV32I_SSP/RV32I_SSP.srcs/sources_1/ip/clk_divider/clk_divider.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/hari/Documents/Projects/RISC-V/Verilog_implementations/RV32I_SSP/RV32I_SSP.srcs/sources_1/ip/clk_divider/clk_divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
